### ISSUE TITLE
Fatal error H5Dget_space

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/mppnccombine-fast#23]
Running this command:
```
$ pwd
/home/502/aph502/v45_short/collate_tenth/025
$ /usr/bin/time -v mpirun -n 4 ~/code/c/mppnccombine-fast/mppnccombine-fast -o ocean_barotropic.res.nc --force restart098/ocean_barotropic.res.nc.*
```
Results in this error:
```
[rank 002] Unaligned or compression change (slow) copy of anompb_bar from restart098/ocean_barotropic.res.nc.0438
[rank 000] ERROR in HDF5 async.c:293

HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 0:
  #000: ../../../../src/H5D.c line 373 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
/home/502/aph502/code/c/mppnccombine-fast/mppnccombine-fast[0x4077f1]
/home/502/aph502/code/c/mppnccombine-fast/mppnccombine-fast[0x406d8c]
/home/502/aph502/code/c/mppnccombine-fast/mppnccombine-fast[0x403ee8]
/lib64/libc.so.6(__libc_start_main+0x100)[0x2b5eba8ead20]
/home/502/aph502/code/c/mppnccombine-fast/mppnccombine-fast[0x402f99]
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.
```
These are restart files from an active run, so this is a show-stopper error. Consequently have added it to the release project

**Comment by ScottWales** [comment]
It’s a race in the messages in async.c, the close variable message gets received before a write to the same variable. Thought I had fixed by unrolling the receive code, but apparently not.

Though thinking about it closing the variable handle shouldn’t be necessary, might remove that.

On 28 Sep 2018, at 1:25 pm, Aidan Heerdegen <notifications@github.com<mailto:notifications@github.com>> wrote:


This sounds a bit similar:

JuliaIO/HDF5.jl#36<https://github.com/JuliaIO/HDF5.jl/issues/36>

possibly due to file handle ids being re-used. Could this be what was diagnosed as a race condition previously @ScottWales<https://github.com/ScottWales>?

**Comment by aidanheerdegen** [comment]
Ok. That has fixed the bug above. 

Do you know the limit on the number of open variables? If this is reached, I assume the collation will `exit` noisily, so the original files won't be deleted? In other words, a known limitation that we can work around if anyone trips it, but won't lead to data loss.
